---
version: 2
jobs:
  build:
    docker:
      - image: library/docker:19-git
    working_directory: /tmp/build
    environment:
      DOCKER_USERNAME: travisciresin
      DOCKER_IMAGE: balena/balena-base-ui
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 18.09.3
      - run: |
          docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - run:
          name: Build
          command: |
            set -x
            docker pull "${DOCKER_IMAGE}:${CIRCLE_BRANCH}" || \
              docker pull "${DOCKER_IMAGE}:master" || true
            docker build --cache-from="${DOCKER_IMAGE}:${CIRCLE_BRANCH}" --cache-from="${DOCKER_IMAGE}:master" --rm=false --pull --tag "${DOCKER_IMAGE}:${CIRCLE_SHA1}" .
      - deploy:
          name: Push
          command: |
            set -x
            docker tag "${DOCKER_IMAGE}:${CIRCLE_SHA1}" "${DOCKER_IMAGE}:${CIRCLE_BRANCH}"
            docker tag "${DOCKER_IMAGE}:${CIRCLE_SHA1}" "${DOCKER_IMAGE}:latest"
            docker push "${DOCKER_IMAGE}:${CIRCLE_SHA1}"
            docker push "${DOCKER_IMAGE}:${CIRCLE_BRANCH}" &
            docker push "${DOCKER_IMAGE}:latest" &

            tag=$(git describe --tags) || true
            if [ "${tag}" != "" ]; then
              docker tag "${DOCKER_IMAGE}:${CIRCLE_SHA1}" "${DOCKER_IMAGE}:${tag}"
              docker push "${DOCKER_IMAGE}:${tag}" &
            fi
            wait
